# Basic
title: lvasky
subtitle: ä¸ªäººç«™
description: ä¸–ç•Œä¸Šåªæœ‰ä¸€ç§çœŸæ­£çš„è‹±é›„ä¸»ä¹‰,é‚£å°±æ˜¯çœ‹æ¸…ç”Ÿæ´»çš„çœŸç›¸ä¹‹å,ä¾ç„¶çƒ­çˆ±ç”Ÿæ´»
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: å¿«ä¹ç”Ÿæ´»æ¯ä¸€å¤©
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: C /C++ /fpga
url: "https://lvasky.github.io"

# åšå®¢æ˜¯å¦è‡ªåŠ¨ç”Ÿæˆç›®å½•ï¼Œfalseä¸ºä¸ç”Ÿæˆ
enableToc: true

# Comment
comment:
     livere: MTAyMC81MzgzMi8zMDMwNQ  # https://www.livere.com
    #disqus: lvasky
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    # weibo: 5366874726 
    github: lvasky
    # zhihu: panpanleopard
    juejin: xxx
    #jianshu: 2ada30d8d0f7
    # twitter: 
    mail: 1254632021@qq.com





# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: æŠ€æœ¯æ”¯æŒ, description: support, url: '/support'}      
    - {title: å…³äºæˆ‘, description: about, url: '/about'}   
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"

